export default tempData=[
    {
        id:1,
        name:"Vegitables",
        color: "#24A6D9",
        todos:[
            {
                title:"Onion",
                completed:false
            },
            {
                title:"Tomato",
                completed:true
            },
            {
                title:"Carrot",
                completed:true
            },
            {
                title:"Beetroot",
                completed:false
            }
        ]
    },
    {
        id:2,
        name:"Groceries",
        color: "#8022D9",
        todos:[
            {
                title:"Salt",
                completed:false
            },
            {
                title:"Sugar",
                completed:true
            },
            {
                title:"Samba rice",
                completed:true
            },
            {
                title:"Tea",
                completed:true
            },
            {
                title:"Parippu",
                completed:true
            }
        ]
    },
    {
        id:3,
        name:"Sweets",
        color: "#595BD9",
        todos:[
            {
                title:"Chocolates",
                completed:false
            },
            {
                title:"Tofees",
                completed:true
            },
            {
                title:"Biscuits",
                completed:true
            }
        ]
    }
];